Update workflows, sever now generates correct url

diff --git a/workflows/upload-conformance.yml b/workflows/upload-conformance.yml
--- a/workflows/upload-conformance.yml
+++ b/workflows/upload-conformance.yml
@@ -49,3 +49,18 @@ jobs:
       - name: "Submit data to server"
         run: |
             curl -H "x-api-key: $API_KEY" -H "event: ${{env.github_event}}" -H "sha: ${{env.commit_sha}}" -H "pr-number: ${{env.pr_number}}" -H "repo: ${{env.original_github_repository}}" -F "file=@${{env.commit_sha}}.json.bz2" $SERVER_URL/upload
+            response=$(curl -s -o temp_response.txt -w "%{http_code}" \
+              -H "x-api-key: $API_KEY" \
+              -H "event: ${{ env.github_event }}" \
+              -H "sha: ${{ env.commit_sha }}" \
+              -H "pr-numer: ${{ env.pr_number }}" \
+              -F "file=@${{env.commit_sha}}.json.bz2" \
+              $SERVER_URL/upload)
+
+            echo "Server response:"
+            cat temp_response.txt
+            echo "HTTP Status: $response"
+            if [ "$response" -gt 200 ]; then
+              echo "Server did not respond with status 200. Failing the workflow."
+              exit 1
+            fi 
